package com.inc.lite.stationdemo.util

data class CountryPhones(
    val name: String,
    val phoneCode: String,
    val code: String = "US"
)

class CountryCodes {

    fun getCountryCodes(lang: Int): List<CountryPhones>{
        return if(lang == 0 ){
            countryCodesEng
        }else{
            countryCodesEng
        }
    }


    val countryCodesEng = listOf(
        CountryPhones("Afghanistan", "+93", "AF"),
        CountryPhones("Albania", "+355", "AL"),
        CountryPhones("Algeria", "+213", "DZ"),
        CountryPhones("Andorra", "+376", "AD"),
        CountryPhones("Angola", "+244", "AO"),
        CountryPhones("Antigua and Barbuda", "+1", "AG"),
        CountryPhones("Argentina", "+54", "AR"),
        CountryPhones("Armenia", "+374", "AM"),
        CountryPhones("Australia", "+61", "AU"),
        CountryPhones("Austria", "+43", "AT"),
        CountryPhones("Azerbaijan", "+994", "AZ"),
        CountryPhones("Bahamas", "+1", "BS"),
        CountryPhones("Bahrain", "+973", "BH"),
        CountryPhones("Bangladesh", "+880", "BD"),
        CountryPhones("Barbados", "+1", "BB"),
        CountryPhones("Belarus", "+375", "BY"),
        CountryPhones("Belgium", "+32", "BE"),
        CountryPhones("Belize", "+501", "BZ"),
        CountryPhones("Benin", "+229", "BJ"),
        CountryPhones("Bhutan", "+975", "BT"),
        CountryPhones("Bolivia", "+591", "BO"),
        CountryPhones("Bosnia and Herzegovina", "+387", "BA"),
        CountryPhones("Botswana", "+267", "BW"),
        CountryPhones("Brazil", "+55", "BR"),
        CountryPhones("Brunei", "+673", "BN"),
        CountryPhones("Bulgaria", "+359", "BG"),
        CountryPhones("Burkina Faso", "+226", "BF"),
        CountryPhones("Burundi", "+257", "BI"),
        CountryPhones("Cabo Verde", "+238", "CV"),
        CountryPhones("Cambodia", "+855", "KH"),
        CountryPhones("Cameroon", "+237", "CM"),
        CountryPhones("Canada", "+1", "CA"),
        CountryPhones("Central African Republic", "+236", "CF"),
        CountryPhones("Chad", "+235", "TD"),
        CountryPhones("Chile", "+56", "CL"),
        CountryPhones("China", "+86", "CN"),
        CountryPhones("Colombia", "+57", "CO"),
        CountryPhones("Comoros", "+269", "KM"),
        CountryPhones("Congo - Brazzaville", "+242", "CG"),
        CountryPhones("Congo - Kinshasa", "+243", "CD"),
        CountryPhones("Costa Rica", "+506", "CR"),
        CountryPhones("Croatia", "+385", "HR"),
        CountryPhones("Cuba", "+53", "CU"),
        CountryPhones("Cyprus", "+357", "CY"),
        CountryPhones("Czech Republic", "+420", "CZ"),
        CountryPhones("Denmark", "+45", "DK"),
        CountryPhones("Djibouti", "+253", "DJ"),
        CountryPhones("Dominica", "+1", "DM"),
        CountryPhones("Dominican Republic", "+1", "DO"),
        CountryPhones("Ecuador", "+593", "EC"),
        CountryPhones("Egypt", "+20", "EG"),
        CountryPhones("El Salvador", "+503", "SV"),
        CountryPhones("Equatorial Guinea", "+240", "GQ"),
        CountryPhones("Eritrea", "+291", "ER"),
        CountryPhones("Estonia", "+372", "EE"),
        CountryPhones("Eswatini", "+268", "SZ"),
        CountryPhones("Ethiopia", "+251", "ET"),
        CountryPhones("Fiji", "+679", "FJ"),
        CountryPhones("Finland", "+358", "FI"),
        CountryPhones("France", "+33", "FR"),
        CountryPhones("Gabon", "+241", "GA"),
        CountryPhones("Gambia", "+220", "GM"),
        CountryPhones("Georgia", "+995", "GE"),
        CountryPhones("Germany", "+49", "DE"),
        CountryPhones("Ghana", "+233", "GH"),
        CountryPhones("Greece", "+30", "GR"),
        CountryPhones("Grenada", "+1", "GD"),
        CountryPhones("Guatemala", "+502", "GT"),
        CountryPhones("Guinea", "+224", "GN"),
        CountryPhones("Guinea-Bissau", "+245", "GW"),
        CountryPhones("Guyana", "+592", "GY"),
        CountryPhones("Haiti", "+509", "HT"),
        CountryPhones("Holy See", "+39", "VA"),
        CountryPhones("Honduras", "+504", "HN"),
        CountryPhones("Hungary", "+36", "HU"),
        CountryPhones("Iceland", "+354", "IS"),
        CountryPhones("India", "+91", "IN"),
        CountryPhones("Indonesia", "+62", "ID"),
        CountryPhones("Iran", "+98", "IR"),
        CountryPhones("Iraq", "+964", "IQ"),
        CountryPhones("Ireland", "+353", "IE"),
        CountryPhones("Israel", "+972", "IL"),
        CountryPhones("Italy", "+39", "IT"),
        CountryPhones("Jamaica", "+1", "JM"),
        CountryPhones("Japan", "+81", "JP"),
        CountryPhones("Jordan", "+962", "JO"),
        CountryPhones("Kazakhstan", "+7", "KZ"),
        CountryPhones("Kenya", "+254", "KE"),
        CountryPhones("Kiribati", "+686", "KI"),
        CountryPhones("Kuwait", "+965", "KW"),
        CountryPhones("Kyrgyzstan", "+996", "KG"),
        CountryPhones("Laos", "+856", "LA"),
        CountryPhones("Latvia", "+371", "LV"),
        CountryPhones("Lebanon", "+961", "LB"),
        CountryPhones("Lesotho", "+266", "LS"),
        CountryPhones("Liberia", "+231", "LR"),
        CountryPhones("Libya", "+218", "LY"),
        CountryPhones("Liechtenstein", "+423", "LI"),
        CountryPhones("Lithuania", "+370", "LT"),
        CountryPhones("Luxembourg", "+352", "LU"),
        CountryPhones("Madagascar", "+261", "MG"),
        CountryPhones("Malawi", "+265", "MW"),
        CountryPhones("Malaysia", "+60", "MY"),
        CountryPhones("Maldives", "+960", "MV"),
        CountryPhones("Mali", "+223", "ML"),
        CountryPhones("Malta", "+356", "MT"),
        CountryPhones("Marshall Islands", "+692", "MH"),
        CountryPhones("Mauritania", "+222", "MR"),
        CountryPhones("Mauritius", "+230", "MU"),
        CountryPhones("Mexico", "+52", "MX"),
        CountryPhones("Micronesia", "+691", "FM"),
        CountryPhones("Moldova", "+373", "MD"),
        CountryPhones("Monaco", "+377", "MC"),
        CountryPhones("Mongolia", "+976", "MN"),
        CountryPhones("Montenegro", "+382", "ME"),
        CountryPhones("Morocco", "+212", "MA"),
        CountryPhones("Mozambique", "+258", "MZ"),
        CountryPhones("Myanmar", "+95", "MM"),
        CountryPhones("Namibia", "+264", "NA"),
        CountryPhones("Nauru", "+674", "NR"),
        CountryPhones("Nepal", "+977", "NP"),
        CountryPhones("Netherlands", "+31", "NL"),
        CountryPhones("New Zealand", "+64", "NZ"),
        CountryPhones("Nicaragua", "+505", "NI"),
        CountryPhones("Niger", "+227", "NE"),
        CountryPhones("Nigeria", "+234", "NG"),
        CountryPhones("North Macedonia", "+389", "MK"),
        CountryPhones("Norway", "+47", "NO"),
        CountryPhones("Oman", "+968", "OM"),
        CountryPhones("Pakistan", "+92", "PK"),
        CountryPhones("Palau", "+680", "PW"),
        CountryPhones("Palestine State", "+970", "PS"),
        CountryPhones("Panama", "+507", "PA"),
        CountryPhones("Papua New Guinea", "+675", "PG"),
        CountryPhones("Paraguay", "+595", "PY"),
        CountryPhones("Peru", "+51", "PE"),
        CountryPhones("Philippines", "+63", "PH"),
        CountryPhones("Poland", "+48", "PL"),
        CountryPhones("Portugal", "+351", "PT"),
        CountryPhones("Qatar", "+974", "QA"),
        CountryPhones("Romania", "+40", "RO"),
        CountryPhones("Russia", "+7", "RU"),
        CountryPhones("Rwanda", "+250", "RW"),
        CountryPhones("St Kitts & Nevis", "+1", "KN"),
        CountryPhones("St Lucia", "+1", "LC"),
        CountryPhones("St Vincent & Grenadines", "+1", "VC"),
        CountryPhones("Samoa", "+685", "WS"),
        CountryPhones("San Marino", "+378", "SM"),
        CountryPhones("Sao Tome & Principe", "+239", "ST"),
        CountryPhones("Saudi Arabia", "+966", "SA"),
        CountryPhones("Senegal", "+221", "SN"),
        CountryPhones("Serbia", "+381", "RS"),
        CountryPhones("Seychelles", "+248", "SC"),
        CountryPhones("Sierra Leone", "+232", "SL"),
        CountryPhones("Singapore", "+65", "SG"),
        CountryPhones("Slovakia", "+421", "SK"),
        CountryPhones("Slovenia", "+386", "SI"),
        CountryPhones("Solomon Islands", "+677", "SB"),
        CountryPhones("Somalia", "+252", "SO"),
        CountryPhones("South Africa", "+27", "ZA"),
        CountryPhones("South Korea", "+82", "KR"),
        CountryPhones("South Sudan", "+211", "SS"),
        CountryPhones("Spain", "+34", "ES"),
        CountryPhones("Sri Lanka", "+94", "LK"),
        CountryPhones("Sudan", "+249", "SD"),
        CountryPhones("Suriname", "+597", "SR"),
        CountryPhones("Switzerland", "+41", "CH"),
        CountryPhones("Syria", "+963", "SY"),
        CountryPhones("Taiwan", "+886", "TW"),
        CountryPhones("Tajikistan", "+992", "TJ"),
        CountryPhones("Tanzania", "+255", "TZ"),
        CountryPhones("Thailand", "+66", "TH"),
        CountryPhones("Timor-Leste", "+670", "TL"),
        CountryPhones("Togo", "+228", "TG"),
        CountryPhones("Tonga", "+676", "TO"),
        CountryPhones("Trinidad and Tobago", "+1", "TT"),
        CountryPhones("Tunisia", "+216", "TN"),
        CountryPhones("Turkey", "+90", "TR"),
        CountryPhones("Turkmenistan", "+993", "TM"),
        CountryPhones("Tuvalu", "+688", "TV"),
        CountryPhones("Uganda", "+256", "UG"),
        CountryPhones("Ukraine", "+380", "UA"),
        CountryPhones("United Arab Emirates", "+971", "AE"),
        CountryPhones("United Kingdom", "+44", "GB"),
        CountryPhones("United States of America", "+1", "US"),
        CountryPhones("Uruguay", "+598", "UY"),
        CountryPhones("Uzbekistan", "+998", "UZ"),
        CountryPhones("Vanuatu", "+678", "VU"),
        CountryPhones("Venezuela", "+58", "VE"),
        CountryPhones("Vietnam", "+84", "VN"),
        CountryPhones("Yemen", "+967", "YE"),
        CountryPhones("Zambia", "+260", "ZM"),
        CountryPhones("Zimbabwe", "+263", "ZW")
    )

    val countryCodesChinees = listOf(
        CountryPhones("阿富汗", "+93", "AF"),
        CountryPhones("阿爾巴尼亞", "+355", "AL"),
        CountryPhones("阿爾及利亞", "+213", "DZ"),
        CountryPhones("安道爾", "+376", "AD"),
        CountryPhones("安哥拉", "+244", "AO"),
        CountryPhones("安地卡及巴布達", "+1", "AG"),
        CountryPhones("阿根廷", "+54", "AR"),
        CountryPhones("亞美尼亞", "+374", "AM"),
        CountryPhones("澳洲", "+61", "AU"),
        CountryPhones("奧地利", "+43", "AT"),
        CountryPhones("亞塞拜然", "+994", "AZ"),
        CountryPhones("巴哈馬", "+1", "BS"),
        CountryPhones("巴林", "+973", "BH"),
        CountryPhones("孟加拉", "+880", "BD"),
        CountryPhones("巴巴多斯", "+1", "BB"),
        CountryPhones("白俄羅斯", "+375", "BY"),
        CountryPhones("比利時", "+32", "BE"),
        CountryPhones("貝里斯", "+501", "BZ"),
        CountryPhones("貝南", "+229", "BJ"),
        CountryPhones("不丹", "+975", "BT"),
        CountryPhones("玻利維亞", "+591", "BO"),
        CountryPhones("波斯尼亞和黑塞哥維那", "+387", "BA"),
        CountryPhones("博茨瓦納", "+267", "BW"),
        CountryPhones("巴西", "+55", "BR"),
        CountryPhones("汶萊", "+673", "BN"),
        CountryPhones("保加利亞", "+359", "BG"),
        CountryPhones("布吉納法索", "+226", "BF"),
        CountryPhones("布隆迪", "+257", "BI"),
        CountryPhones("佛得角", "+238", "CV"),
        CountryPhones("柬埔寨", "+855", "KH"),
        CountryPhones("喀麥隆", "+237", "CM"),
        CountryPhones("加拿大", "+1", "CA"),
        CountryPhones("中非共和國", "+236", "CF"),
        CountryPhones("查德", "+235", "TD"),
        CountryPhones("智利", "+56", "CL"),
        CountryPhones("中國", "+86", "CN"),
        CountryPhones("哥倫比亞", "+57", "CO"),
        CountryPhones("科摩羅", "+269", "KM"),
        CountryPhones("剛果 - 布拉薩", "+242", "CG"),
        CountryPhones("剛果 - 金夏沙", "+243", "CD"),
        CountryPhones("哥斯達黎加", "+506", "CR"),
        CountryPhones("克羅地亞", "+385", "HR"),
        CountryPhones("古巴", "+53", "CU"),
        CountryPhones("塞浦路斯", "+357", "CY"),
        CountryPhones("捷克共和國", "+420", "CZ"),
        CountryPhones("丹麥", "+45", "DK"),
        CountryPhones("吉布提", "+253", "DJ"),
        CountryPhones("多米尼克", "+1", "DM"),
        CountryPhones("多明尼加", "+1", "DO"),
        CountryPhones("厄瓜多", "+593", "EC"),
        CountryPhones("埃及", "+20", "EG"),
        CountryPhones("薩爾瓦多", "+503", "SV"),
        CountryPhones("赤道幾內亞", "+240", "GQ"),
        CountryPhones("厄利垂亞", "+291", "ER"),
        CountryPhones("愛沙尼亞", "+372", "EE"),
        CountryPhones("史瓦帝尼", "+268", "SZ"),
        CountryPhones("衣索比亞", "+251", "ET"),
        CountryPhones("斐濟", "+679", "FJ"),
        CountryPhones("芬蘭", "+358", "FI"),
        CountryPhones("法國", "+33", "FR"),
        CountryPhones("加彭", "+241", "GA"),
        CountryPhones("甘比亞", "+220", "GM"),
        CountryPhones("喬治亞", "+995", "GE"),
        CountryPhones("德國", "+49", "DE"),
        CountryPhones("迦納", "+233", "GH"),
        CountryPhones("希臘", "+30", "GR"),
        CountryPhones("格瑞那達", "+1", "GD"),
        CountryPhones("瓜地馬拉", "+502", "GT"),
        CountryPhones("幾內亞", "+224", "GN"),
        CountryPhones("幾內亞比索", "+245", "GW"),
        CountryPhones("蓋亞那", "+592", "GY"),
        CountryPhones("海地", "+509", "HT"),
        CountryPhones("教廷", "+39", "VA"),
        CountryPhones("洪都拉斯", "+504", "HN"),
        CountryPhones("匈牙利", "+36", "HU"),
        CountryPhones("冰島", "+354", "IS"),
        CountryPhones("印度", "+91", "IN"),
        CountryPhones("印尼", "+62", "ID"),
        CountryPhones("伊朗", "+98", "IR"),
        CountryPhones("伊拉克", "+964", "IQ"),
        CountryPhones("愛爾蘭", "+353", "IE"),
        CountryPhones("以色列", "+972", "IL"),
        CountryPhones("義大利", "+39", "IT"),
        CountryPhones("牙買加", "+1", "JM"),
        CountryPhones("日本", "+81", "JP"),
        CountryPhones("約旦", "+962", "JO"),
        CountryPhones("哈薩克", "+7", "KZ"),
        CountryPhones("肯亞", "+254", "KE"),
        CountryPhones("吉里巴斯", "+686", "KI"),
        CountryPhones("科威特", "+965", "KW"),
        CountryPhones("吉爾吉斯", "+996", "KG"),
        CountryPhones("寮國", "+856", "LA"),
        CountryPhones("拉脫維亞", "+371", "LV"),
        CountryPhones("黎巴嫩", "+961", "LB"),
        CountryPhones("賴索托", "+266", "LS"),
        CountryPhones("賴比瑞亞", "+231", "LR"),
        CountryPhones("利比亞", "+218", "LY"),
        CountryPhones("列支敦斯登", "+423", "LI"),
        CountryPhones("立陶宛", "+370", "LT"),
        CountryPhones("盧森堡", "+352", "LU"),
        CountryPhones("馬達加斯加", "+261", "MG"),
        CountryPhones("馬拉威", "+265", "MW"),
        CountryPhones("馬來西亞", "+60", "MY"),
        CountryPhones("馬爾地夫", "+960", "MV"),
        CountryPhones("馬里", "+223", "ML"),
        CountryPhones("馬爾他", "+356", "MT"),
        CountryPhones("馬紹爾群島", "+692", "MH"),
        CountryPhones("茅利塔尼亞", "+222", "MR"),
        CountryPhones("模里西斯", "+230", "MU"),
        CountryPhones("墨西哥", "+52", "MX"),
        CountryPhones("密克羅尼西亞聯邦", "+691", "FM"),
        CountryPhones("摩爾多瓦", "+373", "MD"),
        CountryPhones("摩納哥", "+377", "MC"),
        CountryPhones("蒙古", "+976", "MN"),
        CountryPhones("蒙特內哥羅", "+382", "ME"),
        CountryPhones("摩洛哥", "+212", "MA"),
        CountryPhones("莫三比克", "+258", "MZ"),
        CountryPhones("緬甸", "+95", "MM"),
        CountryPhones("納米比亞", "+264", "NA"),
        CountryPhones("諾魯", "+674", "NR"),
        CountryPhones("尼泊爾", "+977", "NP"),
        CountryPhones("荷蘭", "+31", "NL"),
        CountryPhones("紐西蘭", "+64", "NZ"),
        CountryPhones("尼加拉瓜", "+505", "NI"),
        CountryPhones("尼日", "+227", "NE"),
        CountryPhones("尼日利亞", "+234", "NG"),
        CountryPhones("北馬其頓", "+389", "MK"),
        CountryPhones("挪威", "+47", "NO"),
        CountryPhones("阿曼", "+968", "OM"),
        CountryPhones("巴基斯坦", "+92", "PK"),
        CountryPhones("帛琉", "+680", "PW"),
        CountryPhones("巴勒斯坦", "+970", "PS"),
        CountryPhones("巴拿馬", "+507", "PA"),
        CountryPhones("巴布亞新幾內亞", "+675", "PG"),
        CountryPhones("巴拉圭", "+595", "PY"),
        CountryPhones("祕魯", "+51", "PE"),
        CountryPhones("菲律賓", "+63", "PH"),
        CountryPhones("波蘭", "+48", "PL"),
        CountryPhones("葡萄牙", "+351", "PT"),
        CountryPhones("卡達", "+974", "QA"),
        CountryPhones("羅馬尼亞", "+40", "RO"),
        CountryPhones("俄羅斯", "+7", "RU"),
        CountryPhones("盧安達", "+250", "RW"),
        CountryPhones("聖基茨和尼維斯", "+1", "KN"),
        CountryPhones("聖盧西亞", "+1", "LC"),
        CountryPhones("聖文森及格瑞那丁", "+1", "VC"),
        CountryPhones("薩摩亞", "+685", "WS"),
        CountryPhones("聖馬利諾", "+378", "SM"),
        CountryPhones("聖多美及普林西比", "+239", "ST"),
        CountryPhones("沙烏地阿拉伯", "+966", "SA"),
        CountryPhones("塞內加爾", "+221", "SN"),
        CountryPhones("塞爾維亞", "+381", "RS"),
        CountryPhones("塞席爾", "+248", "SC"),
        CountryPhones("塞拉利昂", "+232", "SL"),
        CountryPhones("新加坡", "+65", "SG"),
        CountryPhones("斯洛伐克", "+421", "SK"),
        CountryPhones("斯洛維尼亞", "+386", "SI"),
        CountryPhones("索羅門群島", "+677", "SB"),
        CountryPhones("索馬利亞", "+252", "SO"),
        CountryPhones("南非", "+27", "ZA"),
        CountryPhones("南韓", "+82", "KR"),
        CountryPhones("南蘇丹", "+211", "SS"),
        CountryPhones("西班牙", "+34", "ES"),
        CountryPhones("斯里蘭卡", "+94", "LK"),
        CountryPhones("蘇丹", "+249", "SD"),
        CountryPhones("蘇利南", "+597", "SR"),
        CountryPhones("瑞士", "+41", "CH"),
        CountryPhones("敘利亞", "+963", "SY"),
        CountryPhones("台灣", "+886", "TW"),
        CountryPhones("塔吉克", "+992", "TJ"),
        CountryPhones("坦尚尼亞", "+255", "TZ"),
        CountryPhones("泰國", "+66", "TH"),
        CountryPhones("東帝汶", "+670", "TL"),
        CountryPhones("多哥", "+228", "TG"),
        CountryPhones("東加", "+676", "TO"),
        CountryPhones("千里達及托巴哥", "+1", "TT"),
        CountryPhones("突尼西亞", "+216", "TN"),
        CountryPhones("土耳其", "+90", "TR"),
        CountryPhones("土庫曼", "+993", "TM"),
        CountryPhones("圖瓦盧", "+688", "TV"),
        CountryPhones("烏干達", "+256", "UG"),
        CountryPhones("烏克蘭", "+380", "UA"),
        CountryPhones("阿拉伯聯合大公國", "+971", "AE"),
        CountryPhones("英國", "+44", "GB"),
        CountryPhones("美利堅合眾國", "+1", "US"),
        CountryPhones("烏拉圭", "+598", "UY"),
        CountryPhones("烏茲別克", "+998", "UZ"),
        CountryPhones("萬那杜", "+678", "VU"),
        CountryPhones("委內瑞拉", "+58", "VE"),
        CountryPhones("越南", "+84", "VN"),
        CountryPhones("葉門", "+967", "YE"),
        CountryPhones("尚比亞", "+260", "ZM"),
        CountryPhones("辛巴威", "+263", "ZW")
    )

//    val countryListEng = listOf(
//        Pair("Afghanistan", "+93"),
//        Pair("Albania", "+355"),
//        Pair("Algeria", "+213"),
//        Pair("Andorra", "+376"),
//        Pair("Angola", "+244"),
//        Pair("Antigua and Barbuda", "+1"),
//        Pair("Argentina", "+54"),
//        Pair("Armenia", "+374"),
//        Pair("Australia", "+61"),
//        Pair("Austria", "+43"),
//        Pair("Azerbaijan", "+994"),
//        Pair("Bahamas", "+1"),
//        Pair("Bahrain", "+973"),
//        Pair("Bangladesh", "+880"),
//        Pair("Barbados", "+1"),
//        Pair("Belarus", "+375"),
//        Pair("Belgium", "+32"),
//        Pair("Belize", "+501"),
//        Pair("Benin", "+229"),
//        Pair("Bhutan", "+975"),
//        Pair("Bolivia", "+591"),
//        Pair("Bosnia and Herzegovina", "+387"),
//        Pair("Botswana", "+267"),
//        Pair("Brazil", "+55"),
//        Pair("Brunei", "+673"),
//        Pair("Bulgaria", "+359"),
//        Pair("Burkina Faso", "+226"),
//        Pair("Burundi", "+257"),
//        Pair("Cabo Verde", "+238"),
//        Pair("Cambodia", "+855"),
//        Pair("Cameroon", "+237"),
//        Pair("Canada", "+1"),
//        Pair("Central African Republic", "+236"),
//        Pair("Chad", "+235"),
//        Pair("Chile", "+56"),
//        Pair("China", "+86"),
//        Pair("Colombia", "+57"),
//        Pair("Comoros", "+269"),
//        Pair("Congo - Brazzaville", "+242"),
//        Pair("Congo - Kinshasa", "+243"),
//        Pair("Costa Rica", "+506"),
//        Pair("Croatia", "+385"),
//        Pair("Cuba", "+53"),
//        Pair("Cyprus", "+357"),
//        Pair("Czech Republic", "+420"),
//        Pair("Denmark", "+45"),
//        Pair("Djibouti", "+253"),
//        Pair("Dominica", "+1"),
//        Pair("Dominican Republic", "+1"),
//        Pair("Ecuador", "+593"),
//        Pair("Egypt", "+20"),
//        Pair("El Salvador", "+503"),
//        Pair("Equatorial Guinea", "+240"),
//        Pair("Eritrea", "+291"),
//        Pair("Estonia", "+372"),
//        Pair("Eswatini", "+268"),
//        Pair("Ethiopia", "+251"),
//        Pair("Fiji", "+679"),
//        Pair("Finland", "+358"),
//        Pair("France", "+33"),
//        Pair("Gabon", "+241"),
//        Pair("Gambia", "+220"),
//        Pair("Georgia", "+995"),
//        Pair("Germany", "+49"),
//        Pair("Ghana", "+233"),
//        Pair("Greece", "+30"),
//        Pair("Grenada", "+1"),
//        Pair("Guatemala", "+502"),
//        Pair("Guinea", "+224"),
//        Pair("Guinea-Bissau", "+245"),
//        Pair("Guyana", "+592"),
//        Pair("Haiti", "+509"),
//        Pair("Holy See", "+39"),
//        Pair("Honduras", "+504"),
//        Pair("Hungary", "+36"),
//        Pair("Iceland", "+354"),
//        Pair("India", "+91"),
//        Pair("Indonesia", "+62"),
//        Pair("Iran", "+98"),
//        Pair("Iraq", "+964"),
//        Pair("Ireland", "+353"),
//        Pair("Israel", "+972"),
//        Pair("Italy", "+39"),
//        Pair("Jamaica", "+1"),
//        Pair("Japan", "+81"),
//        Pair("Jordan", "+962"),
//        Pair("Kazakhstan", "+7"),
//        Pair("Kenya", "+254"),
//        Pair("Kiribati", "+686"),
//        Pair("Kuwait", "+965"),
//        Pair("Kyrgyzstan", "+996"),
//        Pair("Laos", "+856"),
//        Pair("Latvia", "+371"),
//        Pair("Lebanon", "+961"),
//        Pair("Lesotho", "+266"),
//        Pair("Liberia", "+231"),
//        Pair("Libya", "+218"),
//        Pair("Liechtenstein", "+423"),
//        Pair("Lithuania", "+370"),
//        Pair("Luxembourg", "+352"),
//        Pair("Madagascar", "+261"),
//        Pair("Malawi", "+265"),
//        Pair("Malaysia", "+60"),
//        Pair("Maldives", "+960"),
//        Pair("Mali", "+223"),
//        Pair("Malta", "+356"),
//        Pair("Marshall Islands", "+692"),
//        Pair("Mauritania", "+222"),
//        Pair("Mauritius", "+230"),
//        Pair("Mexico", "+52"),
//        Pair("Micronesia", "+691"),
//        Pair("Moldova", "+373"),
//        Pair("Monaco", "+377"),
//        Pair("Mongolia", "+976"),
//        Pair("Montenegro", "+382"),
//        Pair("Morocco", "+212"),
//        Pair("Mozambique", "+258"),
//        Pair("Myanmar", "+95"),
//        Pair("Namibia", "+264"),
//        Pair("Nauru", "+674"),
//        Pair("Nepal", "+977"),
//        Pair("Netherlands", "+31"),
//        Pair("New Zealand", "+64"),
//        Pair("Nicaragua", "+505"),
//        Pair("Niger", "+227"),
//        Pair("Nigeria", "+234"),
//        Pair("North Korea", "+850"),
//        Pair("North Macedonia", "+389"),
//        Pair("Norway", "+47"),
//        Pair("Oman", "+968"),
//        Pair("Pakistan", "+92"),
//        Pair("Palau", "+680"),
//        Pair("Palestine State", "+970"),
//        Pair("Panama", "+507"),
//        Pair("Papua New Guinea", "+675"),
//        Pair("Paraguay", "+595"),
//        Pair("Peru", "+51"),
//        Pair("Philippines", "+63"),
//        Pair("Poland", "+48"),
//        Pair("Portugal", "+351"),
//        Pair("Qatar", "+974"),
//        Pair("Romania", "+40"),
//        Pair("Russia", "+7"),
//        Pair("Rwanda", "+250"),
//        Pair("St Kitts & Nevis", "+1"),
//        Pair("St Lucia", "+1"),
//        Pair("St Vincent & Grenadines", "+1"),
//        Pair("Samoa", "+685"),
//        Pair("San Marino", "+378"),
//        Pair("Sao Tome & Principe", "+239"),
//        Pair("Saudi Arabia", "+966"),
//        Pair("Senegal", "+221"),
//        Pair("Serbia", "+381"),
//        Pair("Seychelles", "+248"),
//        Pair("Sierra Leone", "+232"),
//        Pair("Singapore", "+65"),
//        Pair("Slovakia", "+421"),
//        Pair("Slovenia", "+386"),
//        Pair("Solomon Islands", "+677"),
//        Pair("Somalia", "+252"),
//        Pair("South Africa", "+27"),
//        Pair("South Korea", "+82"),
//        Pair("South Sudan", "+211"),
//        Pair("Spain", "+34"),
//        Pair("Sri Lanka", "+94"),
//        Pair("Sudan", "+249"),
//        Pair("Suriname", "+597"),
//        Pair("Switzerland", "+41"),
//        Pair("Syria", "+963"),
//        Pair("Taiwan", "+886"),
//        Pair("Tajikistan", "+992"),
//        Pair("Tanzania", "+255"),
//        Pair("Thailand", "+66"),
//        Pair("Timor-Leste", "+670"),
//        Pair("Togo", "+228"),
//        Pair("Tonga", "+676"),
//        Pair("Trinidad and Tobago", "+1"),
//        Pair("Tunisia", "+216"),
//        Pair("Turkey", "+90"),
//        Pair("Turkmenistan", "+993"),
//        Pair("Tuvalu", "+688"),
//        Pair("Uganda", "+256"),
//        Pair("Ukraine", "+380"),
//        Pair("United Arab Emirates", "+971"),
//        Pair("United Kingdom", "+44"),
//        Pair("United States of America", "+1"),
//        Pair("Uruguay", "+598"),
//        Pair("Uzbekistan", "+998"),
//        Pair("Vanuatu", "+678"),
//        Pair("Venezuela", "+58"),
//        Pair("Vietnam", "+84"),
//        Pair("Yemen", "+967"),
//        Pair("Zambia", "+260"),
//        Pair("Zimbabwe", "+263")
//    )
//
//    val countryListChinese = listOf(
//        Pair("阿富汗", "+93"),
//        Pair("阿尔巴尼亚", "+355"),
//        Pair("阿尔及利亚", "+213"),
//        Pair("安道尔", "+376"),
//        Pair("安哥拉", "+244"),
//        Pair("安提瓜和巴布达", "+1"),
//        Pair("阿根廷", "+54"),
//        Pair("亚美尼亚", "+374"),
//        Pair("澳大利亚", "+61"),
//        Pair("奥地利", "+43"),
//        Pair("阿塞拜疆", "+994"),
//        Pair("巴哈马", "+1"),
//        Pair("巴林", "+973"),
//        Pair("孟加拉", "+880"),
//        Pair("巴巴多斯", "+1"),
//        Pair("白俄罗斯", "+375"),
//        Pair("比利时", "+32"),
//        Pair("伯利兹", "+501"),
//        Pair("贝宁", "+229"),
//        Pair("不丹", "+975"),
//        Pair("玻利维亚", "+591"),
//        Pair("波斯尼亚和黑塞哥维那", "+387"),
//        Pair("博茨瓦纳", "+267"),
//        Pair("巴西", "+55"),
//        Pair("文莱", "+673"),
//        Pair("保加利亚", "+359"),
//        Pair("布基纳法索", "+226"),
//        Pair("布隆迪", "+257"),
//        Pair("佛得角", "+238"),
//        Pair("柬埔寨", "+855"),
//        Pair("喀麦隆", "+237"),
//        Pair("加拿大", "+1"),
//        Pair("中非共和国", "+236"),
//        Pair("乍得", "+235"),
//        Pair("智利", "+56"),
//        Pair("中国", "+86"),
//        Pair("哥伦比亚", "+57"),
//        Pair("科摩罗", "+269"),
//        Pair("刚果（布）", "+242"),
//        Pair("哥斯达黎加", "+506"),
//        Pair("克罗地亚", "+385"),
//        Pair("古巴", "+53"),
//        Pair("塞浦路斯", "+357"),
//        Pair("捷克共和国", "+420"),
//        Pair("刚果（金）", "+243"),
//        Pair("丹麦", "+45"),
//        Pair("吉布提", "+253"),
//        Pair("多米尼克", "+1"),
//
//
//        Pair("多米尼加共和国", "+1"),
//        Pair("厄瓜多尔", "+593"),
//        Pair("埃及", "+20"),
//        Pair("萨尔瓦多", "+503"),
//        Pair("赤道几内亚", "+240"),
//        Pair("厄立特里亚", "+291"),
//        Pair("爱沙尼亚", "+372"),
//        Pair("斯威士兰", "+268"),
//        Pair("埃塞俄比亚", "+251"),
//        Pair("斐济", "+679"),
//        Pair("芬兰", "+358"),
//        Pair("法国", "+33"),
//        Pair("加蓬", "+241"),
//        Pair("冈比亚", "+220"),
//        Pair("格鲁吉亚", "+995"),
//        Pair("德国", "+49"),
//        Pair("加纳", "+233"),
//        Pair("希腊", "+30"),
//        Pair("格林纳达", "+1"),
//        Pair("危地马拉", "+502"),
//        Pair("几内亚", "+224"),
//        Pair("几内亚比绍", "+245"),
//        Pair("圭亚那", "+592"),
//        Pair("海地", "+509"),
//        Pair("梵蒂冈", "+39"),
//        Pair("洪都拉斯", "+504"),
//        Pair("匈牙利", "+36"),
//        Pair("冰岛", "+354"),
//        Pair("印度", "+91"),
//        Pair("印度尼西亚", "+62"),
//        Pair("伊朗", "+98"),
//        Pair("伊拉克", "+964"),
//        Pair("爱尔兰", "+353"),
//        Pair("以色列", "+972"),
//        Pair("意大利", "+39"),
//        Pair("牙买加", "+1"),
//        Pair("日本", "+81"),
//        Pair("约旦", "+962"),
//        Pair("哈萨克斯坦", "+7"),
//        Pair("肯尼亚", "+254"),
//        Pair("基里巴斯", "+686"),
//        Pair("科威特", "+965"),
//        Pair("吉尔吉斯斯坦", "+996"),
//        Pair("老挝", "+856"),
//        Pair("台灣", "+886"),
//        Pair("拉脱维亚", "+371"),
//        Pair("黎巴嫩", "+961"),
//        Pair("莱索托", "+266"),
//        Pair("利比里亚", "+231"),
//        Pair("利比亚", "+218"),
//        Pair("列支敦士登", "+423"),
//        Pair("立陶宛", "+370"),
//        Pair("卢森堡", "+352"),
//        Pair("马达加斯加", "+261"),
//        Pair("马拉维", "+265"),
//        Pair("马来西亚", "+60"),
//        Pair("马尔代夫", "+960"),
//        Pair("马里", "+223"),
//        Pair("马耳他", "+356"),
//        Pair("马绍尔群岛", "+692"),
//        Pair("毛里塔尼亚", "+222"),
//        Pair("毛里求斯", "+230"),
//        Pair("墨西哥", "+52"),
//        Pair("密克罗尼西亚", "+691"),
//
//
//        Pair("摩尔多瓦", "+373"),
//        Pair("摩纳哥", "+377"),
//        Pair("蒙古", "+976"),
//        Pair("黑山", "+382"),
//        Pair("摩洛哥", "+212"),
//        Pair("莫桑比克", "+258"),
//        Pair("缅甸（前缅甸）", "+95"),
//        Pair("纳米比亚", "+264"),
//        Pair("瑙鲁", "+674"),
//        Pair("尼泊尔", "+977"),
//        Pair("荷兰", "+31"),
//        Pair("新西兰", "+64"),
//        Pair("尼加拉瓜", "+505"),
//        Pair("尼日尔", "+227"),
//        Pair("尼日利亚", "+234"),
//        Pair("朝鲜", "+850"),
//        Pair("北马其顿", "+389"),
//        Pair("挪威", "+47"),
//        Pair("阿曼", "+968"),
//        Pair("巴基斯坦", "+92"),
//        Pair("帕劳", "+680"),
//        Pair("巴勒斯坦", "+970"),
//        Pair("巴拿马", "+507"),
//        Pair("巴布亚新几内亚", "+675"),
//        Pair("巴拉圭", "+595"),
//        Pair("秘鲁", "+51"),
//        Pair("菲律宾", "+63"),
//        Pair("波兰", "+48"),
//        Pair("葡萄牙", "+351"),
//        Pair("卡塔尔", "+974"),
//        Pair("罗马尼亚", "+40"),
//        Pair("俄罗斯", "+7"),
//        Pair("卢旺达", "+250"),
//        Pair("圣基茨和尼维斯", "+1"),
//        Pair("圣卢西亚", "+1"),
//        Pair("圣文森特和格林纳丁斯", "+1"),
//        Pair("萨摩亚", "+685"),
//        Pair("圣马力诺", "+378"),
//        Pair("圣多美和普林西比", "+239"),
//        Pair("沙特阿拉伯", "+966"),
//        Pair("塞内加尔", "+221"),
//        Pair("塞尔维亚", "+381"),
//        Pair("塞舌尔", "+248"),
//        Pair("塞拉利昂", "+232"),
//        Pair("新加坡", "+65"),
//        Pair("斯洛伐克", "+421"),
//        Pair("斯洛文尼亚", "+386"),
//        Pair("所罗门群岛", "+677"),
//        Pair("索马里", "+252"),
//        Pair("南非", "+27"),
//        Pair("韩国", "+82"),
//        Pair("南苏丹", "+211"),
//        Pair("西班牙", "+34"),
//        Pair("斯里兰卡", "+94"),
//        Pair("苏丹", "+249"),
//        Pair("苏里南", "+597"),
//        Pair("瑞士", "+41"),
//        Pair("叙利亚", "+963"),
//        Pair("塔吉克斯坦", "+992"),
//        Pair("坦桑尼亚", "+255"),
//        Pair("泰国", "+66"),
//        Pair("东帝汶", "+670"),
//        Pair("多哥", "+228"),
//        Pair("汤加", "+676"),
//        Pair("特立尼达和多巴哥", "+1"),
//        Pair("突尼斯", "+216"),
//        Pair("土耳其", "+90"),
//        Pair("土库曼斯坦", "+993"),
//        Pair("图瓦卢", "+688"),
//        Pair("乌干达", "+256"),
//        Pair("乌克兰", "+380"),
//        Pair("阿联酋", "+971"),
//        Pair("英国", "+44"),
//        Pair("美国", "+1"),
//        Pair("乌拉圭", "+598"),
//        Pair("乌兹别克斯坦", "+998"),
//        Pair("瓦努阿图", "+678"),
//        Pair("委内瑞拉", "+58"),
//        Pair("越南", "+84"),
//        Pair("也门", "+967"),
//        Pair("赞比亚", "+260"),
//        Pair("津巴布韦", "+263")
//    )
}
