package com.inc.lite.stationdemo.util

class CountryCodes {

    val countryListEng = listOf(
        Pair("Afghanistan", "+93"),
        Pair("Albania", "+355"),
        Pair("Algeria", "+213"),
        Pair("Andorra", "+376"),
        Pair("Angola", "+244"),
        Pair("Antigua and Barbuda", "+1"),
        Pair("Argentina", "+54"),
        Pair("Armenia", "+374"),
        Pair("Australia", "+61"),
        Pair("Austria", "+43"),
        Pair("Azerbaijan", "+994"),
        Pair("Bahamas", "+1"),
        Pair("Bahrain", "+973"),
        Pair("Bangladesh", "+880"),
        Pair("Barbados", "+1"),
        Pair("Belarus", "+375"),
        Pair("Belgium", "+32"),
        Pair("Belize", "+501"),
        Pair("Benin", "+229"),
        Pair("Bhutan", "+975"),
        Pair("Bolivia", "+591"),
        Pair("Bosnia and Herzegovina", "+387"),
        Pair("Botswana", "+267"),
        Pair("Brazil", "+55"),
        Pair("Brunei", "+673"),
        Pair("Bulgaria", "+359"),
        Pair("Burkina Faso", "+226"),
        Pair("Burundi", "+257"),
        Pair("Cabo Verde", "+238"),
        Pair("Cambodia", "+855"),
        Pair("Cameroon", "+237"),
        Pair("Canada", "+1"),
        Pair("Central African Republic", "+236"),
        Pair("Chad", "+235"),
        Pair("Chile", "+56"),
        Pair("China", "+86"),
        Pair("Colombia", "+57"),
        Pair("Comoros", "+269"),
        Pair("Congo - Brazzaville", "+242"),
        Pair("Congo - Kinshasa", "+243"),
        Pair("Costa Rica", "+506"),
        Pair("Croatia", "+385"),
        Pair("Cuba", "+53"),
        Pair("Cyprus", "+357"),
        Pair("Czech Republic", "+420"),
        Pair("Denmark", "+45"),
        Pair("Djibouti", "+253"),
        Pair("Dominica", "+1"),
        Pair("Dominican Republic", "+1"),
        Pair("Ecuador", "+593"),
        Pair("Egypt", "+20"),
        Pair("El Salvador", "+503"),
        Pair("Equatorial Guinea", "+240"),
        Pair("Eritrea", "+291"),
        Pair("Estonia", "+372"),
        Pair("Eswatini", "+268"),
        Pair("Ethiopia", "+251"),
        Pair("Fiji", "+679"),
        Pair("Finland", "+358"),
        Pair("France", "+33"),
        Pair("Gabon", "+241"),
        Pair("Gambia", "+220"),
        Pair("Georgia", "+995"),
        Pair("Germany", "+49"),
        Pair("Ghana", "+233"),
        Pair("Greece", "+30"),
        Pair("Grenada", "+1"),
        Pair("Guatemala", "+502"),
        Pair("Guinea", "+224"),
        Pair("Guinea-Bissau", "+245"),
        Pair("Guyana", "+592"),
        Pair("Haiti", "+509"),
        Pair("Holy See", "+39"),
        Pair("Honduras", "+504"),
        Pair("Hungary", "+36"),
        Pair("Iceland", "+354"),
        Pair("India", "+91"),
        Pair("Indonesia", "+62"),
        Pair("Iran", "+98"),
        Pair("Iraq", "+964"),
        Pair("Ireland", "+353"),
        Pair("Israel", "+972"),
        Pair("Italy", "+39"),
        Pair("Jamaica", "+1"),
        Pair("Japan", "+81"),
        Pair("Jordan", "+962"),
        Pair("Kazakhstan", "+7"),
        Pair("Kenya", "+254"),
        Pair("Kiribati", "+686"),
        Pair("Kuwait", "+965"),
        Pair("Kyrgyzstan", "+996"),
        Pair("Laos", "+856"),
        Pair("Latvia", "+371"),
        Pair("Lebanon", "+961"),
        Pair("Lesotho", "+266"),
        Pair("Liberia", "+231"),
        Pair("Libya", "+218"),
        Pair("Liechtenstein", "+423"),
        Pair("Lithuania", "+370"),
        Pair("Luxembourg", "+352"),
        Pair("Madagascar", "+261"),
        Pair("Malawi", "+265"),
        Pair("Malaysia", "+60"),
        Pair("Maldives", "+960"),
        Pair("Mali", "+223"),
        Pair("Malta", "+356"),
        Pair("Marshall Islands", "+692"),
        Pair("Mauritania", "+222"),
        Pair("Mauritius", "+230"),
        Pair("Mexico", "+52"),
        Pair("Micronesia", "+691"),
        Pair("Moldova", "+373"),
        Pair("Monaco", "+377"),
        Pair("Mongolia", "+976"),
        Pair("Montenegro", "+382"),
        Pair("Morocco", "+212"),
        Pair("Mozambique", "+258"),
        Pair("Myanmar", "+95"),
        Pair("Namibia", "+264"),
        Pair("Nauru", "+674"),
        Pair("Nepal", "+977"),
        Pair("Netherlands", "+31"),
        Pair("New Zealand", "+64"),
        Pair("Nicaragua", "+505"),
        Pair("Niger", "+227"),
        Pair("Nigeria", "+234"),
        Pair("North Korea", "+850"),
        Pair("North Macedonia", "+389"),
        Pair("Norway", "+47"),
        Pair("Oman", "+968"),
        Pair("Pakistan", "+92"),
        Pair("Palau", "+680"),
        Pair("Palestine State", "+970"),
        Pair("Panama", "+507"),
        Pair("Papua New Guinea", "+675"),
        Pair("Paraguay", "+595"),
        Pair("Peru", "+51"),
        Pair("Philippines", "+63"),
        Pair("Poland", "+48"),
        Pair("Portugal", "+351"),
        Pair("Qatar", "+974"),
        Pair("Romania", "+40"),
        Pair("Russia", "+7"),
        Pair("Rwanda", "+250"),
        Pair("St Kitts & Nevis", "+1"),
        Pair("St Lucia", "+1"),
        Pair("St Vincent & Grenadines", "+1"),
        Pair("Samoa", "+685"),
        Pair("San Marino", "+378"),
        Pair("Sao Tome & Principe", "+239"),
        Pair("Saudi Arabia", "+966"),
        Pair("Senegal", "+221"),
        Pair("Serbia", "+381"),
        Pair("Seychelles", "+248"),
        Pair("Sierra Leone", "+232"),
        Pair("Singapore", "+65"),
        Pair("Slovakia", "+421"),
        Pair("Slovenia", "+386"),
        Pair("Solomon Islands", "+677"),
        Pair("Somalia", "+252"),
        Pair("South Africa", "+27"),
        Pair("South Korea", "+82"),
        Pair("South Sudan", "+211"),
        Pair("Spain", "+34"),
        Pair("Sri Lanka", "+94"),
        Pair("Sudan", "+249"),
        Pair("Suriname", "+597"),
        Pair("Switzerland", "+41"),
        Pair("Syria", "+963"),
        Pair("Taiwan", "+886"),
        Pair("Tajikistan", "+992"),
        Pair("Tanzania", "+255"),
        Pair("Thailand", "+66"),
        Pair("Timor-Leste", "+670"),
        Pair("Togo", "+228"),
        Pair("Tonga", "+676"),
        Pair("Trinidad and Tobago", "+1"),
        Pair("Tunisia", "+216"),
        Pair("Turkey", "+90"),
        Pair("Turkmenistan", "+993"),
        Pair("Tuvalu", "+688"),
        Pair("Uganda", "+256"),
        Pair("Ukraine", "+380"),
        Pair("United Arab Emirates", "+971"),
        Pair("United Kingdom", "+44"),
        Pair("United States of America", "+1"),
        Pair("Uruguay", "+598"),
        Pair("Uzbekistan", "+998"),
        Pair("Vanuatu", "+678"),
        Pair("Venezuela", "+58"),
        Pair("Vietnam", "+84"),
        Pair("Yemen", "+967"),
        Pair("Zambia", "+260"),
        Pair("Zimbabwe", "+263")
    )

    val countryListChinese = listOf(
        Pair("阿富汗", "+93"),
        Pair("阿尔巴尼亚", "+355"),
        Pair("阿尔及利亚", "+213"),
        Pair("安道尔", "+376"),
        Pair("安哥拉", "+244"),
        Pair("安提瓜和巴布达", "+1"),
        Pair("阿根廷", "+54"),
        Pair("亚美尼亚", "+374"),
        Pair("澳大利亚", "+61"),
        Pair("奥地利", "+43"),
        Pair("阿塞拜疆", "+994"),
        Pair("巴哈马", "+1"),
        Pair("巴林", "+973"),
        Pair("孟加拉", "+880"),
        Pair("巴巴多斯", "+1"),
        Pair("白俄罗斯", "+375"),
        Pair("比利时", "+32"),
        Pair("伯利兹", "+501"),
        Pair("贝宁", "+229"),
        Pair("不丹", "+975"),
        Pair("玻利维亚", "+591"),
        Pair("波斯尼亚和黑塞哥维那", "+387"),
        Pair("博茨瓦纳", "+267"),
        Pair("巴西", "+55"),
        Pair("文莱", "+673"),
        Pair("保加利亚", "+359"),
        Pair("布基纳法索", "+226"),
        Pair("布隆迪", "+257"),
        Pair("佛得角", "+238"),
        Pair("柬埔寨", "+855"),
        Pair("喀麦隆", "+237"),
        Pair("加拿大", "+1"),
        Pair("中非共和国", "+236"),
        Pair("乍得", "+235"),
        Pair("智利", "+56"),
        Pair("中国", "+86"),
        Pair("哥伦比亚", "+57"),
        Pair("科摩罗", "+269"),
        Pair("刚果（布）", "+242"),
        Pair("哥斯达黎加", "+506"),
        Pair("克罗地亚", "+385"),
        Pair("古巴", "+53"),
        Pair("塞浦路斯", "+357"),
        Pair("捷克共和国", "+420"),
        Pair("刚果（金）", "+243"),
        Pair("丹麦", "+45"),
        Pair("吉布提", "+253"),
        Pair("多米尼克", "+1"),
        Pair("多米尼加共和国", "+1"),
        Pair("厄瓜多尔", "+593"),
        Pair("埃及", "+20"),
        Pair("萨尔瓦多", "+503"),
        Pair("赤道几内亚", "+240"),
        Pair("厄立特里亚", "+291"),
        Pair("爱沙尼亚", "+372"),
        Pair("斯威士兰", "+268"),
        Pair("埃塞俄比亚", "+251"),
        Pair("斐济", "+679"),
        Pair("芬兰", "+358"),
        Pair("法国", "+33"),
        Pair("加蓬", "+241"),
        Pair("冈比亚", "+220"),
        Pair("格鲁吉亚", "+995"),
        Pair("德国", "+49"),
        Pair("加纳", "+233"),
        Pair("希腊", "+30"),
        Pair("格林纳达", "+1"),
        Pair("危地马拉", "+502"),
        Pair("几内亚", "+224"),
        Pair("几内亚比绍", "+245"),
        Pair("圭亚那", "+592"),
        Pair("海地", "+509"),
        Pair("梵蒂冈", "+39"),
        Pair("洪都拉斯", "+504"),
        Pair("匈牙利", "+36"),
        Pair("冰岛", "+354"),
        Pair("印度", "+91"),
        Pair("印度尼西亚", "+62"),
        Pair("伊朗", "+98"),
        Pair("伊拉克", "+964"),
        Pair("爱尔兰", "+353"),
        Pair("以色列", "+972"),
        Pair("意大利", "+39"),
        Pair("牙买加", "+1"),
        Pair("日本", "+81"),
        Pair("约旦", "+962"),
        Pair("哈萨克斯坦", "+7"),
        Pair("肯尼亚", "+254"),
        Pair("基里巴斯", "+686"),
        Pair("科威特", "+965"),
        Pair("吉尔吉斯斯坦", "+996"),
        Pair("老挝", "+856"),
        Pair("台灣", "+886"),
        Pair("拉脱维亚", "+371"),
        Pair("黎巴嫩", "+961"),
        Pair("莱索托", "+266"),
        Pair("利比里亚", "+231"),
        Pair("利比亚", "+218"),
        Pair("列支敦士登", "+423"),
        Pair("立陶宛", "+370"),
        Pair("卢森堡", "+352"),
        Pair("马达加斯加", "+261"),
        Pair("马拉维", "+265"),
        Pair("马来西亚", "+60"),
        Pair("马尔代夫", "+960"),
        Pair("马里", "+223"),
        Pair("马耳他", "+356"),
        Pair("马绍尔群岛", "+692"),
        Pair("毛里塔尼亚", "+222"),
        Pair("毛里求斯", "+230"),
        Pair("墨西哥", "+52"),
        Pair("密克罗尼西亚", "+691"),
        Pair("摩尔多瓦", "+373"),
        Pair("摩纳哥", "+377"),
        Pair("蒙古", "+976"),
        Pair("黑山", "+382"),
        Pair("摩洛哥", "+212"),
        Pair("莫桑比克", "+258"),
        Pair("缅甸（前缅甸）", "+95"),
        Pair("纳米比亚", "+264"),
        Pair("瑙鲁", "+674"),
        Pair("尼泊尔", "+977"),
        Pair("荷兰", "+31"),
        Pair("新西兰", "+64"),
        Pair("尼加拉瓜", "+505"),
        Pair("尼日尔", "+227"),
        Pair("尼日利亚", "+234"),
        Pair("朝鲜", "+850"),
        Pair("北马其顿", "+389"),
        Pair("挪威", "+47"),
        Pair("阿曼", "+968"),
        Pair("巴基斯坦", "+92"),
        Pair("帕劳", "+680"),
        Pair("巴勒斯坦", "+970"),
        Pair("巴拿马", "+507"),
        Pair("巴布亚新几内亚", "+675"),
        Pair("巴拉圭", "+595"),
        Pair("秘鲁", "+51"),
        Pair("菲律宾", "+63"),
        Pair("波兰", "+48"),
        Pair("葡萄牙", "+351"),
        Pair("卡塔尔", "+974"),
        Pair("罗马尼亚", "+40"),
        Pair("俄罗斯", "+7"),
        Pair("卢旺达", "+250"),
        Pair("圣基茨和尼维斯", "+1"),
        Pair("圣卢西亚", "+1"),
        Pair("圣文森特和格林纳丁斯", "+1"),
        Pair("萨摩亚", "+685"),
        Pair("圣马力诺", "+378"),
        Pair("圣多美和普林西比", "+239"),
        Pair("沙特阿拉伯", "+966"),
        Pair("塞内加尔", "+221"),
        Pair("塞尔维亚", "+381"),
        Pair("塞舌尔", "+248"),
        Pair("塞拉利昂", "+232"),
        Pair("新加坡", "+65"),
        Pair("斯洛伐克", "+421"),
        Pair("斯洛文尼亚", "+386"),
        Pair("所罗门群岛", "+677"),
        Pair("索马里", "+252"),
        Pair("南非", "+27"),
        Pair("韩国", "+82"),
        Pair("南苏丹", "+211"),
        Pair("西班牙", "+34"),
        Pair("斯里兰卡", "+94"),
        Pair("苏丹", "+249"),
        Pair("苏里南", "+597"),
        Pair("瑞士", "+41"),
        Pair("叙利亚", "+963"),
        Pair("塔吉克斯坦", "+992"),
        Pair("坦桑尼亚", "+255"),
        Pair("泰国", "+66"),
        Pair("东帝汶", "+670"),
        Pair("多哥", "+228"),
        Pair("汤加", "+676"),
        Pair("特立尼达和多巴哥", "+1"),
        Pair("突尼斯", "+216"),
        Pair("土耳其", "+90"),
        Pair("土库曼斯坦", "+993"),
        Pair("图瓦卢", "+688"),
        Pair("乌干达", "+256"),
        Pair("乌克兰", "+380"),
        Pair("阿联酋", "+971"),
        Pair("英国", "+44"),
        Pair("美国", "+1"),
        Pair("乌拉圭", "+598"),
        Pair("乌兹别克斯坦", "+998"),
        Pair("瓦努阿图", "+678"),
        Pair("委内瑞拉", "+58"),
        Pair("越南", "+84"),
        Pair("也门", "+967"),
        Pair("赞比亚", "+260"),
        Pair("津巴布韦", "+263")
    )
}
