package com.inc.lite.stationdemo.util

data class CountryCode(
    val countryName: String,
    val code: String,
    val numberSize: Int
)

class CountryCodes {

    fun getCountryCodes(lang: Int): List<CountryCode>{
        return if(lang == 0 ){
            countryCodesEng
        }else{
            countryCodesEng
        }
    }


    val countryCodesEng = listOf(
        CountryCode("Afghanistan", "+93", 9),
        CountryCode("Albania", "+355", 9),
        CountryCode("Algeria", "+213", 9),
        CountryCode("Andorra", "+376", 9),
        CountryCode("Angola", "+244", 9),
        CountryCode("Antigua and Barbuda", "+1", 10),
        CountryCode("Argentina", "+54", 10),
        CountryCode("Armenia", "+374", 8),
        CountryCode("Australia", "+61", 9),
        CountryCode("Austria", "+43", 10),
        CountryCode("Azerbaijan", "+994", 9),
        CountryCode("Bahamas", "+1", 10),
        CountryCode("Bahrain", "+973", 8),
        CountryCode("Bangladesh", "+880", 10),
        CountryCode("Barbados", "+1", 10),
        CountryCode("Belarus", "+375", 9),
        CountryCode("Belgium", "+32", 9),
        CountryCode("Belize", "+501", 7),
        CountryCode("Benin", "+229", 8),
        CountryCode("Bhutan", "+975", 8),
        CountryCode("Bolivia", "+591", 8),
        CountryCode("Bosnia and Herzegovina", "+387", 8),
        CountryCode("Botswana", "+267", 8),
        CountryCode("Brazil", "+55", 11),
        CountryCode("Brunei", "+673", 8),
        CountryCode("Bulgaria", "+359", 9),
        CountryCode("Burkina Faso", "+226", 8),
        CountryCode("Burundi", "+257", 8),
        CountryCode("Cabo Verde", "+238", 7),
        CountryCode("Cambodia", "+855", 9),
        CountryCode("Cameroon", "+237", 9),
        CountryCode("Canada", "+1", 10),
        CountryCode("Central African Republic", "+236", 8),
        CountryCode("Chad", "+235", 8),
        CountryCode("Chile", "+56", 9),
        CountryCode("China", "+86", 11),
        CountryCode("Colombia", "+57", 10),
        CountryCode("Comoros", "+269", 7),
        CountryCode("Congo - Brazzaville", "+242", 9),
        CountryCode("Congo - Kinshasa", "+243", 9),
        CountryCode("Costa Rica", "+506", 8),
        CountryCode("Croatia", "+385", 9),
        CountryCode("Cuba", "+53", 8),
        CountryCode("Cyprus", "+357", 8),
        CountryCode("Czech Republic", "+420", 9),
        CountryCode("Denmark", "+45", 8),
        CountryCode("Djibouti", "+253", 8),
        CountryCode("Dominica", "+1", 10),
        CountryCode("Dominican Republic", "+1", 10),
        CountryCode("Ecuador", "+593", 9),
        CountryCode("Egypt", "+20", 10),
        CountryCode("El Salvador", "+503", 8),
        CountryCode("Equatorial Guinea", "+240", 9),
        CountryCode("Eritrea", "+291", 9),
        CountryCode("Estonia", "+372", 9),
        CountryCode("Eswatini", "+268", 8),
        CountryCode("Ethiopia", "+251", 10),
        CountryCode("Fiji", "+679", 8),
        CountryCode("Finland", "+358", 10),
        CountryCode("France", "+33", 11),
        CountryCode("Gabon", "+241", 9),
        CountryCode("Gambia", "+220", 8),
        CountryCode("Georgia", "+995", 9),
        CountryCode("Germany", "+49", 11),
        CountryCode("Ghana", "+233", 9),
        CountryCode("Greece", "+30", 10),
        CountryCode("Grenada", "+1", 10),
        CountryCode("Guatemala", "+502", 8),
        CountryCode("Guinea", "+224", 9),
        CountryCode("Guinea-Bissau", "+245", 8),
        CountryCode("Guyana", "+592", 8),
        CountryCode("Haiti", "+509", 8),
        CountryCode("Holy See", "+39", 11),
        CountryCode("Honduras", "+504", 8),
        CountryCode("Hungary", "+36", 9),
        CountryCode("Iceland", "+354", 9),
        CountryCode("India", "+91", 10),
        CountryCode("Indonesia", "+62", 11),
        CountryCode("Iran", "+98", 11),
        CountryCode("Iraq", "+964", 10),
        CountryCode("Ireland", "+353", 10),
        CountryCode("Israel", "+972", 10),
        CountryCode("Italy", "+39", 11),
        CountryCode("Jamaica", "+1", 10),
        CountryCode("Japan", "+81", 10),
        CountryCode("Jordan", "+962", 9),
        CountryCode("Kazakhstan", "+7", 10),
        CountryCode("Kenya", "+254", 9),
        CountryCode("Kiribati", "+686", 7),
        CountryCode("Kuwait", "+965", 8),
        CountryCode("Kyrgyzstan", "+996", 9),
        CountryCode("Laos", "+856", 9),
        CountryCode("Latvia", "+371", 8),
        CountryCode("Lebanon", "+961", 8),
        CountryCode("Lesotho", "+266", 8),
        CountryCode("Liberia", "+231", 8),
        CountryCode("Libya", "+218", 9),
        CountryCode("Liechtenstein", "+423", 8),
        CountryCode("Lithuania", "+370", 8),
        CountryCode("Luxembourg", "+352", 9),
        CountryCode("Madagascar", "+261", 9),
        CountryCode("Malawi", "+265", 9),
        CountryCode("Malaysia", "+60", 9),
        CountryCode("Maldives", "+960", 7),
        CountryCode("Mali", "+223", 8),
        CountryCode("Malta", "+356", 8),
        CountryCode("Marshall Islands", "+692", 7),
        CountryCode("Mauritania", "+222", 9),
        CountryCode("Mauritius", "+230", 9),
        CountryCode("Mexico", "+52", 10),
        CountryCode("Micronesia", "+691", 7),
        CountryCode("Moldova", "+373", 8),
        CountryCode("Monaco", "+377", 9),
        CountryCode("Mongolia", "+976", 8),
        CountryCode("Montenegro", "+382", 10),
        CountryCode("Morocco", "+212", 10),
        CountryCode("Mozambique", "+258", 9),
        CountryCode("Myanmar", "+95", 8),
        CountryCode("Namibia", "+264", 9),
        CountryCode("Nauru", "+674", 7),
        CountryCode("Nepal", "+977", 10),
        CountryCode("Netherlands", "+31", 10),
        CountryCode("New Zealand", "+64", 10),
        CountryCode("Nicaragua", "+505", 8),
        CountryCode("Niger", "+227", 8),
        CountryCode("Nigeria", "+234", 10),
        CountryCode("North Korea", "+850", 10),
        CountryCode("North Macedonia", "+389", 9),
        CountryCode("Norway", "+47", 9),
        CountryCode("Oman", "+968", 8),
        CountryCode("Pakistan", "+92", 10),
        CountryCode("Palau", "+680", 7),
        CountryCode("Palestine State", "+970", 9),
        CountryCode("Panama", "+507", 8),
        CountryCode("Papua New Guinea", "+675", 9),
        CountryCode("Paraguay", "+595", 10),
        CountryCode("Peru", "+51", 9),
        CountryCode("Philippines", "+63", 10),
        CountryCode("Poland", "+48", 9),
        CountryCode("Portugal", "+351", 9),
        CountryCode("Qatar", "+974", 8),
        CountryCode("Romania", "+40", 10),
        CountryCode("Russia", "+7", 10),
        CountryCode("Rwanda", "+250", 9),
        CountryCode("St Kitts & Nevis", "+1", 10),
        CountryCode("St Lucia", "+1", 10),
        CountryCode("St Vincent & Grenadines", "+1", 10),
        CountryCode("Samoa", "+685", 7),
        CountryCode("San Marino", "+378", 9),
        CountryCode("Sao Tome & Principe", "+239", 8),
        CountryCode("Saudi Arabia", "+966", 9),
        CountryCode("Senegal", "+221", 9),
        CountryCode("Serbia", "+381", 9),
        CountryCode("Seychelles", "+248", 7),
        CountryCode("Sierra Leone", "+232", 8),
        CountryCode("Singapore", "+65", 8),
        CountryCode("Slovakia", "+421", 9),
        CountryCode("Slovenia", "+386", 9),
        CountryCode("Solomon Islands", "+677", 7),
        CountryCode("Somalia", "+252", 9),
        CountryCode("South Africa", "+27", 9),
        CountryCode("South Korea", "+82", 10),
        CountryCode("South Sudan", "+211", 9),
        CountryCode("Spain", "+34", 9),
        CountryCode("Sri Lanka", "+94", 10),
        CountryCode("Sudan", "+249", 10),
        CountryCode("Suriname", "+597", 8),
        CountryCode("Switzerland", "+41", 9),
        CountryCode("Syria", "+963", 9),
        CountryCode("Taiwan", "+886", 9),
        CountryCode("Tajikistan", "+992", 9),
        CountryCode("Tanzania", "+255", 10),
        CountryCode("Thailand", "+66", 9),
        CountryCode("Timor-Leste", "+670", 8),
        CountryCode("Togo", "+228", 8),
        CountryCode("Tonga", "+676", 7),
        CountryCode("Trinidad and Tobago", "+1", 10),
        CountryCode("Tunisia", "+216", 8),
        CountryCode("Turkey", "+90", 10),
        CountryCode("Turkmenistan", "+993", 8),
        CountryCode("Tuvalu", "+688", 6),
        CountryCode("Uganda", "+256", 9),
        CountryCode("Ukraine", "+380", 9),
        CountryCode("United Arab Emirates", "+971", 9),
        CountryCode("United Kingdom", "+44", 10),
        CountryCode("United States of America", "+1", 10),
        CountryCode("Uruguay", "+598", 9),
        CountryCode("Uzbekistan", "+998", 9),
        CountryCode("Vanuatu", "+678", 7),
        CountryCode("Venezuela", "+58", 10),
        CountryCode("Vietnam", "+84", 10),
        CountryCode("Yemen", "+967", 9),
        CountryCode("Zambia", "+260", 9),
        CountryCode("Zimbabwe", "+263", 9)
    )

    val countryCodesChz = listOf(
        CountryCode("阿富汗", "+93", 9),
        CountryCode("阿尔巴尼亚", "+355", 10),
        CountryCode("阿尔及利亚", "+213", 10),
        CountryCode("安道尔", "+376", 8),
        CountryCode("安哥拉", "+244", 9),
        CountryCode("安提瓜和巴布达", "+1", 10),
        CountryCode("阿根廷", "+54", 10),
        CountryCode("亚美尼亚", "+374", 9),
        CountryCode("澳大利亚", "+61", 10),
        CountryCode("奥地利", "+43", 10),
        CountryCode("阿塞拜疆", "+994", 10),
        CountryCode("巴哈马", "+1", 10),
        CountryCode("巴林", "+973", 9),
        CountryCode("孟加拉", "+880", 10),
        CountryCode("巴巴多斯", "+1", 10),
        CountryCode("白俄罗斯", "+375", 9),
        CountryCode("比利时", "+32", 9),
        CountryCode("伯利兹", "+501", 8),
        CountryCode("贝宁", "+229", 9),
        CountryCode("不丹", "+975", 9),
        CountryCode("玻利维亚", "+591", 10),
        CountryCode("波斯尼亚和黑塞哥维那", "+387", 10),
        CountryCode("博茨瓦纳", "+267", 9),
        CountryCode("巴西", "+55", 11),
        CountryCode("文莱", "+673", 9),
        CountryCode("保加利亚", "+359", 10),
        CountryCode("布基纳法索", "+226", 9),
        CountryCode("布隆迪", "+257", 9),
        CountryCode("佛得角", "+238", 7),
        CountryCode("柬埔寨", "+855", 9),
        CountryCode("喀麦隆", "+237", 9),
        CountryCode("加拿大", "+1", 10),
        CountryCode("中非共和国", "+236", 9),
        CountryCode("乍得", "+235", 8),
        CountryCode("智利", "+56", 9),
        CountryCode("中国", "+86", 11),
        CountryCode("哥伦比亚", "+57", 10),
        CountryCode("科摩罗", "+269", 9),
        CountryCode("刚果（布）", "+242", 10),
        CountryCode("哥斯达黎加", "+506", 9),
        CountryCode("克罗地亚", "+385", 9),
        CountryCode("古巴", "+53", 8),
        CountryCode("塞浦路斯", "+357", 9),
        CountryCode("捷克共和国", "+420", 9),
        CountryCode("刚果（金）", "+243", 9),
        CountryCode("丹麦", "+45", 8),
        CountryCode("吉布提", "+253", 9),
        CountryCode("多米尼克", "+1", 10),
        CountryCode("多米尼加共和国", "+1", 10),
        CountryCode("厄瓜多尔", "+593", 10),
        CountryCode("埃及", "+20", 10),
        CountryCode("萨尔瓦多", "+503", 10),
        CountryCode("赤道几内亚", "+240", 9),
        CountryCode("厄立特里亚", "+291", 9),
        CountryCode("爱沙尼亚", "+372", 9),
        CountryCode("斯威士兰", "+268", 9),
        CountryCode("埃塞俄比亚", "+251", 10),
        CountryCode("斐济", "+679", 9),
        CountryCode("芬兰", "+358", 10),
        CountryCode("法国", "+33", 9),
        CountryCode("加蓬", "+241", 9),
        CountryCode("冈比亚", "+220", 9),
        CountryCode("格鲁吉亚", "+995", 9),
        CountryCode("德国", "+49", 11),
        CountryCode("加纳", "+233", 9),
        CountryCode("希腊", "+30", 10),
        CountryCode("格林纳达", "+1", 10),
        CountryCode("危地马拉", "+502", 10),
        CountryCode("几内亚", "+224", 10),
        CountryCode("几内亚比绍", "+245", 10),
        CountryCode("圭亚那", "+592", 9),
        CountryCode("海地", "+509", 10),
        CountryCode("梵蒂冈", "+39", 9),
        CountryCode("洪都拉斯", "+504", 10),
        CountryCode("匈牙利", "+36", 10),
        CountryCode("冰岛", "+354", 9),
        CountryCode("印度", "+91", 10),
        CountryCode("印度尼西亚", "+62", 11),
        CountryCode("伊朗", "+98", 11),
        CountryCode("伊拉克", "+964", 10),
        CountryCode("爱尔兰", "+353", 9),
        CountryCode("以色列", "+972", 10),
        CountryCode("意大利", "+39", 11),
        CountryCode("牙买加", "+1", 10),
        CountryCode("日本", "+81", 10),
        CountryCode("约旦", "+962", 9),
        CountryCode("哈萨克斯坦", "+7", 10),
        CountryCode("肯尼亚", "+254", 10),
        CountryCode("基里巴斯", "+686", 9),
        CountryCode("科威特", "+965", 9),
        CountryCode("吉尔吉斯斯坦", "+996", 10),
        CountryCode("老挝", "+856", 9),
        CountryCode("台灣", "+886", 10),
        CountryCode("拉脱维亚", "+371", 9),
        CountryCode("黎巴嫩", "+961", 9),
        CountryCode("莱索托", "+266", 9),
        CountryCode("利比里亚", "+231", 9),
        CountryCode("利比亚", "+218", 9),
        CountryCode("列支敦士登", "+423", 9),
        CountryCode("立陶宛", "+370", 9),
        CountryCode("卢森堡", "+352", 9),
        CountryCode("马达加斯加", "+261", 10),
        CountryCode("马拉维", "+265", 9),
        CountryCode("马来西亚", "+60", 10),
        CountryCode("马尔代夫", "+960", 9),
        CountryCode("马里", "+223", 9),
        CountryCode("马耳他", "+356", 9),
        CountryCode("马绍尔群岛", "+692", 9),
        CountryCode("毛里塔尼亚", "+222", 9),
        CountryCode("毛里求斯", "+230", 9),
        CountryCode("墨西哥", "+52", 11),
        CountryCode("密克罗尼西亚", "+691", 9),
        CountryCode("摩尔多瓦", "+373", 9),
        CountryCode("摩纳哥", "+377", 9),
        CountryCode("蒙古", "+976", 10),
        CountryCode("黑山", "+382", 9),
        CountryCode("摩洛哥", "+212", 11),
        CountryCode("莫桑比克", "+258", 9),
        CountryCode("缅甸（前缅甸）", "+95", 9),
        CountryCode("纳米比亚", "+264", 9),
        CountryCode("瑙鲁", "+674", 7),
        CountryCode("尼泊尔", "+977", 10),
        CountryCode("荷兰", "+31", 10),
        CountryCode("新西兰", "+64", 10),
        CountryCode("尼加拉瓜", "+505", 9),
        CountryCode("尼日尔", "+227", 9),
        CountryCode("尼日利亚", "+234", 10),
        CountryCode("朝鲜", "+850", 9),
        CountryCode("北马其顿", "+389", 9),
        CountryCode("挪威", "+47", 10),
        CountryCode("阿曼", "+968", 10),
        CountryCode("巴基斯坦", "+92", 11),
        CountryCode("帕劳", "+680", 9),
        CountryCode("巴勒斯坦", "+970", 10),
        CountryCode("巴拿马", "+507", 10),
        CountryCode("巴布亚新几内亚", "+675", 10),
        CountryCode("巴拉圭", "+595", 10),
        CountryCode("秘鲁", "+51", 10),
        CountryCode("菲律宾", "+63", 10),
        CountryCode("波兰", "+48", 9),
        CountryCode("葡萄牙", "+351", 10),
        CountryCode("卡塔尔", "+974", 10),
        CountryCode("罗马尼亚", "+40", 10),
        CountryCode("俄罗斯", "+7", 10),
        CountryCode("卢旺达", "+250", 9),
        CountryCode("圣基茨和尼维斯", "+1", 10),
        CountryCode("圣卢西亚", "+1", 10),
        CountryCode("圣文森特和格林纳丁斯", "+1", 10),
        CountryCode("萨摩亚", "+685", 7),
        CountryCode("圣马力诺", "+378", 9),
        CountryCode("圣多美和普林西比", "+239", 10),
        CountryCode("沙特阿拉伯", "+966", 10),
        CountryCode("塞内加尔", "+221", 9),
        CountryCode("塞尔维亚", "+381", 10),
        CountryCode("塞舌尔", "+248", 9),
        CountryCode("塞拉利昂", "+232", 9),
        CountryCode("新加坡", "+65", 10),
        CountryCode("斯洛伐克", "+421", 9),
        CountryCode("斯洛文尼亚", "+386", 10),
        CountryCode("所罗门群岛", "+677", 9),
        CountryCode("索马里", "+252", 9),
        CountryCode("南非", "+27", 9),
        CountryCode("韩国", "+82", 10),
        CountryCode("南苏丹", "+211", 10),
        CountryCode("西班牙", "+34", 10),
        CountryCode("斯里兰卡", "+94", 10),
        CountryCode("苏丹", "+249", 10),
        CountryCode("苏里南", "+597", 9),
        CountryCode("瑞士", "+41", 9),
        CountryCode("叙利亚", "+963", 10),
        CountryCode("塔吉克斯坦", "+992", 10),
        CountryCode("坦桑尼亚", "+255", 10),
        CountryCode("泰国", "+66", 10),
        CountryCode("东帝汶", "+670", 9),
        CountryCode("多哥", "+228", 9),
        CountryCode("汤加", "+676", 9),
        CountryCode("特立尼达和多巴哥", "+1", 10),
        CountryCode("突尼斯", "+216", 9),
        CountryCode("土耳其", "+90", 10),
        CountryCode("土库曼斯坦", "+993", 10),
        CountryCode("图瓦卢", "+688", 9),
        CountryCode("乌干达", "+256", 10),
        CountryCode("乌克兰", "+380", 10),
        CountryCode("阿联酋", "+971", 10),
        CountryCode("英国", "+44", 10),
        CountryCode("美国", "+1", 10),
        CountryCode("乌拉圭", "+598", 10),
        CountryCode("乌兹别克斯坦", "+998", 10),
        CountryCode("瓦努阿图", "+678", 9),
        CountryCode("委内瑞拉", "+58", 10),
        CountryCode("越南", "+84", 10),
        CountryCode("也门", "+967", 9),
        CountryCode("赞比亚", "+260", 10),
        CountryCode("津巴布韦", "+263", 9)
    )

    val countryListEng = listOf(
        Pair("Afghanistan", "+93"),
        Pair("Albania", "+355"),
        Pair("Algeria", "+213"),
        Pair("Andorra", "+376"),
        Pair("Angola", "+244"),
        Pair("Antigua and Barbuda", "+1"),
        Pair("Argentina", "+54"),
        Pair("Armenia", "+374"),
        Pair("Australia", "+61"),
        Pair("Austria", "+43"),
        Pair("Azerbaijan", "+994"),
        Pair("Bahamas", "+1"),
        Pair("Bahrain", "+973"),
        Pair("Bangladesh", "+880"),
        Pair("Barbados", "+1"),
        Pair("Belarus", "+375"),
        Pair("Belgium", "+32"),
        Pair("Belize", "+501"),
        Pair("Benin", "+229"),
        Pair("Bhutan", "+975"),
        Pair("Bolivia", "+591"),
        Pair("Bosnia and Herzegovina", "+387"),
        Pair("Botswana", "+267"),
        Pair("Brazil", "+55"),
        Pair("Brunei", "+673"),
        Pair("Bulgaria", "+359"),
        Pair("Burkina Faso", "+226"),
        Pair("Burundi", "+257"),
        Pair("Cabo Verde", "+238"),
        Pair("Cambodia", "+855"),
        Pair("Cameroon", "+237"),
        Pair("Canada", "+1"),
        Pair("Central African Republic", "+236"),
        Pair("Chad", "+235"),
        Pair("Chile", "+56"),
        Pair("China", "+86"),
        Pair("Colombia", "+57"),
        Pair("Comoros", "+269"),
        Pair("Congo - Brazzaville", "+242"),
        Pair("Congo - Kinshasa", "+243"),
        Pair("Costa Rica", "+506"),
        Pair("Croatia", "+385"),
        Pair("Cuba", "+53"),
        Pair("Cyprus", "+357"),
        Pair("Czech Republic", "+420"),
        Pair("Denmark", "+45"),
        Pair("Djibouti", "+253"),
        Pair("Dominica", "+1"),
        Pair("Dominican Republic", "+1"),
        Pair("Ecuador", "+593"),
        Pair("Egypt", "+20"),
        Pair("El Salvador", "+503"),
        Pair("Equatorial Guinea", "+240"),
        Pair("Eritrea", "+291"),
        Pair("Estonia", "+372"),
        Pair("Eswatini", "+268"),
        Pair("Ethiopia", "+251"),
        Pair("Fiji", "+679"),
        Pair("Finland", "+358"),
        Pair("France", "+33"),
        Pair("Gabon", "+241"),
        Pair("Gambia", "+220"),
        Pair("Georgia", "+995"),
        Pair("Germany", "+49"),
        Pair("Ghana", "+233"),
        Pair("Greece", "+30"),
        Pair("Grenada", "+1"),
        Pair("Guatemala", "+502"),
        Pair("Guinea", "+224"),
        Pair("Guinea-Bissau", "+245"),
        Pair("Guyana", "+592"),
        Pair("Haiti", "+509"),
        Pair("Holy See", "+39"),
        Pair("Honduras", "+504"),
        Pair("Hungary", "+36"),
        Pair("Iceland", "+354"),
        Pair("India", "+91"),
        Pair("Indonesia", "+62"),
        Pair("Iran", "+98"),
        Pair("Iraq", "+964"),
        Pair("Ireland", "+353"),
        Pair("Israel", "+972"),
        Pair("Italy", "+39"),
        Pair("Jamaica", "+1"),
        Pair("Japan", "+81"),
        Pair("Jordan", "+962"),
        Pair("Kazakhstan", "+7"),
        Pair("Kenya", "+254"),
        Pair("Kiribati", "+686"),
        Pair("Kuwait", "+965"),
        Pair("Kyrgyzstan", "+996"),
        Pair("Laos", "+856"),
        Pair("Latvia", "+371"),
        Pair("Lebanon", "+961"),
        Pair("Lesotho", "+266"),
        Pair("Liberia", "+231"),
        Pair("Libya", "+218"),
        Pair("Liechtenstein", "+423"),
        Pair("Lithuania", "+370"),
        Pair("Luxembourg", "+352"),
        Pair("Madagascar", "+261"),
        Pair("Malawi", "+265"),
        Pair("Malaysia", "+60"),
        Pair("Maldives", "+960"),
        Pair("Mali", "+223"),
        Pair("Malta", "+356"),
        Pair("Marshall Islands", "+692"),
        Pair("Mauritania", "+222"),
        Pair("Mauritius", "+230"),
        Pair("Mexico", "+52"),
        Pair("Micronesia", "+691"),
        Pair("Moldova", "+373"),
        Pair("Monaco", "+377"),
        Pair("Mongolia", "+976"),
        Pair("Montenegro", "+382"),
        Pair("Morocco", "+212"),
        Pair("Mozambique", "+258"),
        Pair("Myanmar", "+95"),
        Pair("Namibia", "+264"),
        Pair("Nauru", "+674"),
        Pair("Nepal", "+977"),
        Pair("Netherlands", "+31"),
        Pair("New Zealand", "+64"),
        Pair("Nicaragua", "+505"),
        Pair("Niger", "+227"),
        Pair("Nigeria", "+234"),
        Pair("North Korea", "+850"),
        Pair("North Macedonia", "+389"),
        Pair("Norway", "+47"),
        Pair("Oman", "+968"),
        Pair("Pakistan", "+92"),
        Pair("Palau", "+680"),
        Pair("Palestine State", "+970"),
        Pair("Panama", "+507"),
        Pair("Papua New Guinea", "+675"),
        Pair("Paraguay", "+595"),
        Pair("Peru", "+51"),
        Pair("Philippines", "+63"),
        Pair("Poland", "+48"),
        Pair("Portugal", "+351"),
        Pair("Qatar", "+974"),
        Pair("Romania", "+40"),
        Pair("Russia", "+7"),
        Pair("Rwanda", "+250"),
        Pair("St Kitts & Nevis", "+1"),
        Pair("St Lucia", "+1"),
        Pair("St Vincent & Grenadines", "+1"),
        Pair("Samoa", "+685"),
        Pair("San Marino", "+378"),
        Pair("Sao Tome & Principe", "+239"),
        Pair("Saudi Arabia", "+966"),
        Pair("Senegal", "+221"),
        Pair("Serbia", "+381"),
        Pair("Seychelles", "+248"),
        Pair("Sierra Leone", "+232"),
        Pair("Singapore", "+65"),
        Pair("Slovakia", "+421"),
        Pair("Slovenia", "+386"),
        Pair("Solomon Islands", "+677"),
        Pair("Somalia", "+252"),
        Pair("South Africa", "+27"),
        Pair("South Korea", "+82"),
        Pair("South Sudan", "+211"),
        Pair("Spain", "+34"),
        Pair("Sri Lanka", "+94"),
        Pair("Sudan", "+249"),
        Pair("Suriname", "+597"),
        Pair("Switzerland", "+41"),
        Pair("Syria", "+963"),
        Pair("Taiwan", "+886"),
        Pair("Tajikistan", "+992"),
        Pair("Tanzania", "+255"),
        Pair("Thailand", "+66"),
        Pair("Timor-Leste", "+670"),
        Pair("Togo", "+228"),
        Pair("Tonga", "+676"),
        Pair("Trinidad and Tobago", "+1"),
        Pair("Tunisia", "+216"),
        Pair("Turkey", "+90"),
        Pair("Turkmenistan", "+993"),
        Pair("Tuvalu", "+688"),
        Pair("Uganda", "+256"),
        Pair("Ukraine", "+380"),
        Pair("United Arab Emirates", "+971"),
        Pair("United Kingdom", "+44"),
        Pair("United States of America", "+1"),
        Pair("Uruguay", "+598"),
        Pair("Uzbekistan", "+998"),
        Pair("Vanuatu", "+678"),
        Pair("Venezuela", "+58"),
        Pair("Vietnam", "+84"),
        Pair("Yemen", "+967"),
        Pair("Zambia", "+260"),
        Pair("Zimbabwe", "+263")
    )

    val countryListChinese = listOf(
        Pair("阿富汗", "+93"),
        Pair("阿尔巴尼亚", "+355"),
        Pair("阿尔及利亚", "+213"),
        Pair("安道尔", "+376"),
        Pair("安哥拉", "+244"),
        Pair("安提瓜和巴布达", "+1"),
        Pair("阿根廷", "+54"),
        Pair("亚美尼亚", "+374"),
        Pair("澳大利亚", "+61"),
        Pair("奥地利", "+43"),
        Pair("阿塞拜疆", "+994"),
        Pair("巴哈马", "+1"),
        Pair("巴林", "+973"),
        Pair("孟加拉", "+880"),
        Pair("巴巴多斯", "+1"),
        Pair("白俄罗斯", "+375"),
        Pair("比利时", "+32"),
        Pair("伯利兹", "+501"),
        Pair("贝宁", "+229"),
        Pair("不丹", "+975"),
        Pair("玻利维亚", "+591"),
        Pair("波斯尼亚和黑塞哥维那", "+387"),
        Pair("博茨瓦纳", "+267"),
        Pair("巴西", "+55"),
        Pair("文莱", "+673"),
        Pair("保加利亚", "+359"),
        Pair("布基纳法索", "+226"),
        Pair("布隆迪", "+257"),
        Pair("佛得角", "+238"),
        Pair("柬埔寨", "+855"),
        Pair("喀麦隆", "+237"),
        Pair("加拿大", "+1"),
        Pair("中非共和国", "+236"),
        Pair("乍得", "+235"),
        Pair("智利", "+56"),
        Pair("中国", "+86"),
        Pair("哥伦比亚", "+57"),
        Pair("科摩罗", "+269"),
        Pair("刚果（布）", "+242"),
        Pair("哥斯达黎加", "+506"),
        Pair("克罗地亚", "+385"),
        Pair("古巴", "+53"),
        Pair("塞浦路斯", "+357"),
        Pair("捷克共和国", "+420"),
        Pair("刚果（金）", "+243"),
        Pair("丹麦", "+45"),
        Pair("吉布提", "+253"),
        Pair("多米尼克", "+1"),


        Pair("多米尼加共和国", "+1"),
        Pair("厄瓜多尔", "+593"),
        Pair("埃及", "+20"),
        Pair("萨尔瓦多", "+503"),
        Pair("赤道几内亚", "+240"),
        Pair("厄立特里亚", "+291"),
        Pair("爱沙尼亚", "+372"),
        Pair("斯威士兰", "+268"),
        Pair("埃塞俄比亚", "+251"),
        Pair("斐济", "+679"),
        Pair("芬兰", "+358"),
        Pair("法国", "+33"),
        Pair("加蓬", "+241"),
        Pair("冈比亚", "+220"),
        Pair("格鲁吉亚", "+995"),
        Pair("德国", "+49"),
        Pair("加纳", "+233"),
        Pair("希腊", "+30"),
        Pair("格林纳达", "+1"),
        Pair("危地马拉", "+502"),
        Pair("几内亚", "+224"),
        Pair("几内亚比绍", "+245"),
        Pair("圭亚那", "+592"),
        Pair("海地", "+509"),
        Pair("梵蒂冈", "+39"),
        Pair("洪都拉斯", "+504"),
        Pair("匈牙利", "+36"),
        Pair("冰岛", "+354"),
        Pair("印度", "+91"),
        Pair("印度尼西亚", "+62"),
        Pair("伊朗", "+98"),
        Pair("伊拉克", "+964"),
        Pair("爱尔兰", "+353"),
        Pair("以色列", "+972"),
        Pair("意大利", "+39"),
        Pair("牙买加", "+1"),
        Pair("日本", "+81"),
        Pair("约旦", "+962"),
        Pair("哈萨克斯坦", "+7"),
        Pair("肯尼亚", "+254"),
        Pair("基里巴斯", "+686"),
        Pair("科威特", "+965"),
        Pair("吉尔吉斯斯坦", "+996"),
        Pair("老挝", "+856"),
        Pair("台灣", "+886"),
        Pair("拉脱维亚", "+371"),
        Pair("黎巴嫩", "+961"),
        Pair("莱索托", "+266"),
        Pair("利比里亚", "+231"),
        Pair("利比亚", "+218"),
        Pair("列支敦士登", "+423"),
        Pair("立陶宛", "+370"),
        Pair("卢森堡", "+352"),
        Pair("马达加斯加", "+261"),
        Pair("马拉维", "+265"),
        Pair("马来西亚", "+60"),
        Pair("马尔代夫", "+960"),
        Pair("马里", "+223"),
        Pair("马耳他", "+356"),
        Pair("马绍尔群岛", "+692"),
        Pair("毛里塔尼亚", "+222"),
        Pair("毛里求斯", "+230"),
        Pair("墨西哥", "+52"),
        Pair("密克罗尼西亚", "+691"),


        Pair("摩尔多瓦", "+373"),
        Pair("摩纳哥", "+377"),
        Pair("蒙古", "+976"),
        Pair("黑山", "+382"),
        Pair("摩洛哥", "+212"),
        Pair("莫桑比克", "+258"),
        Pair("缅甸（前缅甸）", "+95"),
        Pair("纳米比亚", "+264"),
        Pair("瑙鲁", "+674"),
        Pair("尼泊尔", "+977"),
        Pair("荷兰", "+31"),
        Pair("新西兰", "+64"),
        Pair("尼加拉瓜", "+505"),
        Pair("尼日尔", "+227"),
        Pair("尼日利亚", "+234"),
        Pair("朝鲜", "+850"),
        Pair("北马其顿", "+389"),
        Pair("挪威", "+47"),
        Pair("阿曼", "+968"),
        Pair("巴基斯坦", "+92"),
        Pair("帕劳", "+680"),
        Pair("巴勒斯坦", "+970"),
        Pair("巴拿马", "+507"),
        Pair("巴布亚新几内亚", "+675"),
        Pair("巴拉圭", "+595"),
        Pair("秘鲁", "+51"),
        Pair("菲律宾", "+63"),
        Pair("波兰", "+48"),
        Pair("葡萄牙", "+351"),
        Pair("卡塔尔", "+974"),
        Pair("罗马尼亚", "+40"),
        Pair("俄罗斯", "+7"),
        Pair("卢旺达", "+250"),
        Pair("圣基茨和尼维斯", "+1"),
        Pair("圣卢西亚", "+1"),
        Pair("圣文森特和格林纳丁斯", "+1"),
        Pair("萨摩亚", "+685"),
        Pair("圣马力诺", "+378"),
        Pair("圣多美和普林西比", "+239"),
        Pair("沙特阿拉伯", "+966"),
        Pair("塞内加尔", "+221"),
        Pair("塞尔维亚", "+381"),
        Pair("塞舌尔", "+248"),
        Pair("塞拉利昂", "+232"),
        Pair("新加坡", "+65"),
        Pair("斯洛伐克", "+421"),
        Pair("斯洛文尼亚", "+386"),
        Pair("所罗门群岛", "+677"),
        Pair("索马里", "+252"),
        Pair("南非", "+27"),
        Pair("韩国", "+82"),
        Pair("南苏丹", "+211"),
        Pair("西班牙", "+34"),
        Pair("斯里兰卡", "+94"),
        Pair("苏丹", "+249"),
        Pair("苏里南", "+597"),
        Pair("瑞士", "+41"),
        Pair("叙利亚", "+963"),
        Pair("塔吉克斯坦", "+992"),
        Pair("坦桑尼亚", "+255"),
        Pair("泰国", "+66"),
        Pair("东帝汶", "+670"),
        Pair("多哥", "+228"),
        Pair("汤加", "+676"),
        Pair("特立尼达和多巴哥", "+1"),
        Pair("突尼斯", "+216"),
        Pair("土耳其", "+90"),
        Pair("土库曼斯坦", "+993"),
        Pair("图瓦卢", "+688"),
        Pair("乌干达", "+256"),
        Pair("乌克兰", "+380"),
        Pair("阿联酋", "+971"),
        Pair("英国", "+44"),
        Pair("美国", "+1"),
        Pair("乌拉圭", "+598"),
        Pair("乌兹别克斯坦", "+998"),
        Pair("瓦努阿图", "+678"),
        Pair("委内瑞拉", "+58"),
        Pair("越南", "+84"),
        Pair("也门", "+967"),
        Pair("赞比亚", "+260"),
        Pair("津巴布韦", "+263")
    )
}
